### ISSUE TITLE
Chainsaw conflict

### ISSUE THREAD

**Issue by v3ctordesign** [budak7273/PlantSafeVehicles#1]
The mod conflicts with the chainsaws destruction radious. Once the save file is generated with this the saw has a tiny radious and pretty much ignores the modifier so there's no way to reset it.

**Comment by Th3Fanbus** [comment]
This mod will most likely be obsolete once 1.0 is released anyway, as vehicles will no longer collide with foliage.

**Comment by v3ctordesign** [comment]
Sure, the problem is that the mod breaks the chainsaw NOW :D
(uninstalling the mod and crafting a new saw seem to have fixed the issue)

Btw how do you know that detail about foliage collision? :)

**Comment by Th3Fanbus** [comment]
> Btw how do you know that detail about foliage collision? :)

https://store.steampowered.com/news/app/526870/view/4270057097478183701

**Comment by budak7273** [comment]
I tested in-game and the chainsaw seems to behaving as normal.

- Have you tried uninstalling the mod to see if the problem goes away?
- Have you tried with this as the only installed mod?
- Is your inventory near-full? The chainsaw tries to avoid over-harvest if there is no space in your inventory.

**Comment by v3ctordesign** [comment]
You're right! I'm pretty sure it was just a full inventory. My apologies for misdiagnosing the problem!

**Comment by budak7273** [comment]
All good, have fun!
